CREATE OR REPLACE FUNCTION ISS.FN_GET_BF_INT_DATE (
  -- FROM ~ TO 일수계산
    I_ISSUE_DATE CHAR   -- 발행일
  , I_BASE_DATE  CHAR   -- 기준일
  , I_INT_CYCLE  NUMBER -- 이자주기(월)
  ) RETURN CHAR AS
  T_INT_CNT     NUMBER; -- 이자발생횟수
  T_BF_INT_DATE CHAR(8); -- 직전이자지급일
BEGIN
  T_INT_CNT := TRUNC(MONTHS_BETWEEN(I_BASE_DATE, I_ISSUE_DATE) / I_INT_CYCLE);
  T_BF_INT_DATE := TO_CHAR(ADD_MONTHS(I_ISSUE_DATE, T_INT_CNT*I_INT_CYCLE), 'YYYYMMDD');
  RETURN T_BF_INT_DATE;
END;