CREATE OR REPLACE FUNCTION ISS.FN_INIT_BOND_INFO
  RETURN BOND_INFO%ROWTYPE AS
  T_BOND_INFO BOND_INFO%ROWTYPE;
BEGIN
  T_BOND_INFO.BOND_CODE     := '';
  T_BOND_INFO.BOND_TYPE     := '';
  T_BOND_INFO.ISSUE_DATE    := '';
  T_BOND_INFO.EXPIRE_DATE   := '';
  T_BOND_INFO.INT_CYCLE     := 0;
  T_BOND_INFO.ALLOWED_LIMIT := 0;
  
  RETURN T_BOND_INFO;
END;