CREATE OR REPLACE FUNCTION ISS.FN_CALC_DAYS (
  -- FROM ~ TO 일수계산
    I_FROM_DATE IN CHAR(8)
  , I_TO_DATE   IN CHAR(8)
  ) RETURN NUMBER AS
BEGIN
    RETURN TO_DATE(I_TO_DATE,'YYYYMMDD') - TO_DATE(I_FROM_DATE,'YYYYMMDD');
END;