CREATE OR REPLACE PROCEDURE ISS.PR_INIT_BOND_INFO (
  I_BOND_INFO IN OUT BOND_INFO%ROWTYPE
) IS
BEGIN
  I_BOND_INFO.BOND_CODE     := '';
  I_BOND_INFO.BOND_TYPE     := '';
  I_BOND_INFO.ISSUE_DATE    := '';
  I_BOND_INFO.EXPIRE_DATE   := '';
  I_BOND_INFO.INT_CYCLE     := 0;
  I_BOND_INFO.ALLOWED_LIMIT := 0;
  
END;