
-- 종목 조회
DESC BOND_INFO;
SELECT * FROM BOND_INFO;

-- 채권 조회
DESC EVENT_RESULT_EIR;
SELECT * 
  FROM EVENT_RESULT_EIR;
 WHERE FUND_CODE = :FUND_CODE
 ORDER BY 1,2,3,4,5;

-- 잔고 조회
DESC BOND_BALANCE;
SELECT *
  FROM BOND_BALANCE;
 WHERE FUND_CODE = :FUND_CODE
 ORDER BY BIZ_DATE DESC;

-- 거래내역 조회
DESC BOND_TRADE;
SELECT *
 FROM BOND_TRADE
WHERE FUND_CODE = :FUND_CODE
ORDER BY TRD_DATE, TRD_SEQ, FUND_CODE;

-- 손상내역 조회
DESC BOND_DAMAGE;
SELECT * 
 FROM BOND_DAMAGE
WHERE FUND_CODE = :FUND_CODE;

--INSERT INTO BOND_INFO VALUES('KR_단리채', '3', '20121120', '20141120', 6, 10);

-- 해당 채권의 전체 CF_LIST 조회
SELECT A.BOND_CODE, A.BUY_DATE, A.EVENT_DATE, A.EVENT_TYPE, T.*
  FROM EVENT_RESULT_EIR A, TABLE(A.CF_LIST) T
 WHERE A.FUND_CODE = :FUND_CODE
   AND A.BOND_CODE = 'KR_이표채'
   AND A.BUY_DATE = '20121130'
   AND A.BUY_PRICE = 10623
   AND BALAN_SEQ = 1
   AND EVENT_DATE = '20130520'
   AND EVENT_SEQ = 1
 ORDER BY A.EVENT_DATE, T.BASE_DATE;

-- 해당 채권의 전체 SGF_LIST 조회
SELECT A.BOND_CODE, A.BUY_DATE, A.EVENT_DATE, A.EVENT_TYPE, T.*
  FROM EVENT_RESULT_EIR A, TABLE(A.SGF_LIST) T
 WHERE A.FUND_CODE = 'TEST_0429'
   AND A.BOND_CODE = 'KR_이표채'
   AND A.BUY_DATE = '20121120'
   AND A.BUY_PRICE = 10623
   AND A.BALAN_SEQ = 1
   AND A.EVENT_DATE = '20121120'
   AND A.EVENT_SEQ = 1
   AND A.EVENT_TYPE = '1'
 ORDER BY A.EVENT_DATE, T.BASE_DATE, SEQ;


-- DELETE
--DELETE FROM BOND_INFO WHERE BOND_CODE = 'KR_TKPARK';
--DELETE FROM EVENT_RESULT_EIR WHERE FUND_CODE = 'TEST_0424C';
--DELETE FROM BOND_BALANCE WHERE FUND_CODE = 'TEST_0424C';
--DELETE FROM BOND_TRADE WHERE FUND_CODE = 'TEST_0424C';
--DELETE FROM EVENT_RESULT_N_S_TKP WHERE BOND_CODE = 'KR01234567' AND EVENT_DATE = '20121130' AND EVENT_SEQ = 2;


SELECT * FROM EVENT_RESULT_NESTED_S ORDER BY BOND_CODE;

SELECT A.BOND_CODE, A.BUY_DATE, A.EVENT_DATE, A.EVENT_TYPE, T.*
  FROM EVENT_RESULT_NESTED_S A, TABLE(A.CF_LIST) T
 WHERE A.BUY_DATE = '20121130'
   AND A.BOND_CODE = '20130606'
 ORDER BY A.EVENT_DATE, T.BASE_DATE;


SELECT A.BOND_CODE, A.BUY_DATE, A.EVENT_DATE, A.EVENT_TYPE, T.*
  FROM EVENT_RESULT_NESTED_S A, TABLE(A.SGF_LIST) T
 WHERE A.BUY_DATE = '20121130'
   AND A.BOND_CODE = '20130606'
 ORDER BY T.BASE_DATE, SEQ;








