DECLARE
  T_EVENT_RESULT EVENT_RESULT_EIR%ROWTYPE;
  T_SG_LIST TABLE_SGF_S := NEW TABLE_SGF_S(); -- 상각 LIST
  T_SG_ITEM SGF_TYPE_S; -- 현재상각스케쥴
  T_IDX NUMBER := 0;
  
  CURSOR CUR_EVENT_RESULT IS
      SELECT *
        FROM EVENT_RESULT_EIR A
       WHERE A.FUND_CODE = 'TEST_0429'
         AND A.BOND_CODE = 'KR_이표채'
         AND A.BUY_DATE = '20121120'
         AND A.BUY_PRICE = 10623
         AND A.BALAN_SEQ = 1
         AND A.EVENT_DATE = '20121120'
         AND A.EVENT_SEQ = 1
         AND A.EVENT_TYPE = '1';
BEGIN

  OPEN CUR_EVENT_RESULT;
    FETCH CUR_EVENT_RESULT INTO T_EVENT_RESULT;
    IF CUR_EVENT_RESULT%NOTFOUND THEN
      CLOSE CUR_EVENT_RESULT;
      RAISE_APPLICATION_ERROR(-20011, '오류');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('T_EVENT_RESULT=' || T_EVENT_RESULT.EVENT_DATE);
    
  CLOSE CUR_EVENT_RESULT;
  
  FOR C2 IN T_EVENT_RESULT.SGF_LIST.FIRST..T_EVENT_RESULT.SGF_LIST.LAST LOOP
    DBMS_OUTPUT.PUT_LINE('BASE_DATE=' || T_EVENT_RESULT.SGF_LIST(C2).BASE_DATE);
  
  END LOOP;
  
  
  DBMS_OUTPUT.PUT_LINE('END');
    
END;