DECLARE
  T_BOND_BALANCE   BOND_BALANCE%ROWTYPE;          -- ROWTYPE : ¿‹∞Ì
  T_IDX NUMBER := 1;
  
  CURSOR C_BOND_BALANCE_CUR IS
    SELECT *
      FROM BOND_BALANCE;
BEGIN


  OPEN C_BOND_BALANCE_CUR;
    LOOP
      FETCH C_BOND_BALANCE_CUR INTO T_BOND_BALANCE;
      EXIT WHEN C_BOND_BALANCE_CUR%NOTFOUND;
      
      IF T_IDX = 10 THEN
        GOTO PASS_LOOP;
      END IF;
      DBMS_OUTPUT.PUT_LINE(T_IDX || ', '  || T_BOND_BALANCE.BIZ_DATE);
      
      <<PASS_LOOP>>
      
      T_IDX := T_IDX + 1;
      
    END LOOP;
  CLOSE C_BOND_BALANCE_CUR;
  
  DBMS_OUTPUT.PUT_LINE('END');
    
END;