DECLARE
  T_BOND_BALANCE   BOND_BALANCE%ROWTYPE;          -- ROWTYPE : ¿‹∞Ì
  
  CURSOR C_BOND_BALANCE_CUR IS
    SELECT *
      FROM BOND_BALANCE;
BEGIN


  OPEN C_BOND_BALANCE_CUR;
    LOOP
      FETCH C_BOND_BALANCE_CUR INTO T_BOND_BALANCE;
      EXIT WHEN C_BOND_BALANCE_CUR%NOTFOUND;
      
      DBMS_OUTPUT.PUT_LINE(T_BOND_BALANCE.BIZ_DATE);
      
    END LOOP;
  CLOSE C_BOND_BALANCE_CUR;
  
  DBMS_OUTPUT.PUT_LINE('END');
    
END;