DECLARE
  T_BOND_BALANCE   BOND_BALANCE%ROWTYPE;          -- ROWTYPE : ¿‹∞Ì
  T_SGF_TYPE       TABLE_SGF;
  T_TEST_DATE      CHAR;
  
  CURSOR CUR_BOND_BALANCE IS
      SELECT *
        FROM BOND_BALANCE A
       WHERE A.BIZ_DATE = '20121220'
         AND A.FUND_CODE = 'TEST_0425C'
         AND A.BOND_CODE = 'KR_¿Ã«•√§'
         AND A.BUY_DATE = '20121130'
         AND A.BUY_PRICE = 1000
         AND A.BALAN_SEQ = 1 ;
         
  CURSOR CUR_SANGGAK_LIST IS
      SELECT A.BASE_DATE
        FROM EVENT_RESULT_EIR B
           , TABLE(SGF_LIST) A
       WHERE B.FUND_CODE     = T_BOND_BALANCE.FUND_CODE
         AND B.BOND_CODE     = T_BOND_BALANCE.BOND_CODE
         AND B.BUY_DATE      = T_BOND_BALANCE.BUY_DATE
         AND B.BUY_PRICE     = T_BOND_BALANCE.BUY_PRICE
         AND B.BALAN_SEQ     = T_BOND_BALANCE.BALAN_SEQ
         AND A.BASE_DATE     = T_BOND_BALANCE.BIZ_DATE;
         


BEGIN

  OPEN CUR_BOND_BALANCE;
    LOOP
      FETCH CUR_BOND_BALANCE INTO T_BOND_BALANCE;
      EXIT WHEN CUR_BOND_BALANCE%NOTFOUND;
      
      DBMS_OUTPUT.PUT_LINE('BALANCE=' || T_BOND_BALANCE.BIZ_DATE);
      
      OPEN CUR_SANGGAK_LIST;
        LOOP
          T_SGF_TYPE := NEW T_SGF_TYPE();
          FETCH CUR_SANGGAK_LIST INTO T_SGF_TYPE;
          EXIT WHEN CUR_SANGGAK_LIST%NOTFOUND;
          
          DBMS_OUTPUT.PUT_LINE('SANGGAK_LIST=' || T_TEST_DATE);
        END LOOP;
      CLOSE CUR_SANGGAK_LIST;
      
    END LOOP;
  CLOSE CUR_BOND_BALANCE;
  
  DBMS_OUTPUT.PUT_LINE('END');
    
END;